### ISSUE TITLE
把src目录拷贝下来 报错

### ISSUE THREAD

**Issue by Notdefind** [ray0324/react-toast#3]
![wx20170821-163518](https://user-images.githubusercontent.com/17826565/29510561-cfa07e04-868e-11e7-96d2-563ff06abb1f.png)
<img width="393" alt="wx20170821-163536 2x" src="https://user-images.githubusercontent.com/17826565/29510567-d5c30cde-868e-11e7-84bf-4c29a3d7c03e.png">

**Comment by Notdefind** [comment]
import Toast, { T } from 'components/Toast'; 
根组件这样引用

**Comment by ray0324** [comment]
这个应该不是组件的问题吧   你单独渲染Toast组件试试 用个div包裹下。 babel配置ok的话代码是没问题的
还有  看看代码引入路径有木有问题。我最近抽空封装成一个npm包丢上来吧。我之前一个react-redux项目引入ok的  
![20b6ad62-bc66-42c0-827d-bd616d841a84](https://user-images.githubusercontent.com/5204198/29524104-8ae9d034-86c1-11e7-9686-f26392f070ac.png)

**Comment by Notdefind** [comment]
我现在用的npm引用 没有报错 能打印出方法 
![image](https://user-images.githubusercontent.com/17826565/29597014-88f22ff6-87f2-11e7-873f-51bafb3d1f8a.png)
就是显示不出来

**Comment by Notdefind** [comment]
![image](https://user-images.githubusercontent.com/17826565/29597133-456ca4c2-87f3-11e7-8004-1de74271fd5c.png)
页面有HTML结构但是没有样式 是否因为项目没配置less
